[Application]
FileLogger\Enabled=true
FileLogger\Path=/config/qBittorrent/logs

[BitTorrent]
Session\AlternativeGlobalDLSpeedLimit=2048
Session\AlternativeGlobalUPSpeedLimit=1024
Session\DefaultSavePath=/downloads
Session\GlobalDLSpeedLimit=0
Session\GlobalUPSpeedLimit=0
Session\Port=6883
Session\QueueingSystemEnabled=true
Session\SSL\Port=36201
Session\UseAlternativeGlobalSpeedLimit=false

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
WebUI\Address=*
WebUI\AuthSubnetWhitelist=172.28.0.0/16
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=true
WebUI\MaxAuthenticationFailCount=1000
WebUI\Password_PBKDF2="@ByteArray(/ty6mHZUMhD+3LqYdlQyEA==:sdYbYq3A7Ktc/kHESAz9BKV6/7B1rqGF7mHgv/yAiDSpNqEq8ECWyygWJgBNTlsq7AMXHMKvWBmzl0okyubIGA==)"
WebUI\Port=8080
WebUI\Username=qbadmin
