[Application]
FileLogger\Enabled=true
FileLogger\Path=/config/qBittorrent/logs

[BitTorrent]
Session\AlternativeGlobalDLSpeedLimit=1024
Session\AlternativeGlobalUPSpeedLimit=512
Session\DefaultSavePath=/downloads
Session\GlobalDLSpeedLimit=0
Session\GlobalUPSpeedLimit=0
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=41366
Session\UseAlternativeGlobalSpeedLimit=false

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
WebUI\Address=*
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=true
WebUI\MaxAuthenticationFailCount=1000
WebUI\Password_PBKDF2="@ByteArray(ASNFZ4mrze8BI0VniavN7w==:jQjmZcmhLiITphcJFhtH6trSpiq0M91WSKJvs6Zk9JQWOQdKbqyhoBnZtJkRjUfdGLD6AX3Da2ucbXK0hAhhVw==)"
WebUI\Port=8080
WebUI\Username=admin
