stages:
  - sync

sync_to_github:  
  stage: sync
  script:
    - |
      if ! git remote get-url github; then
        git remote add github https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RauchenwaldC/homebridge-qbittorrent-plugin.git
      fi
    - git push github main --force
  only:
    - master