stages:
  - sync
  - release

sync_to_github:  
  stage: sync
  script:
    - |
      if ! git remote get-url github; then
        git remote add github https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RauchenwaldC/homebridge-qbittorrent-plugin.git
      fi
    - |
      git config user.email "support@c18d.com"  # Set a CI-specific email for the local repo
      git config user.name "CI Runner"          # Set a CI-specific username for the local repo
      git fetch origin master  # Fetch the latest changes from GitLab
      git checkout master       # Switch to the master branch
      git push github master --force  # Push the master branch to GitHub
  only:
    - master

create_github_release:
  stage: release
  script:
    - |
      TAG_NAME="${CI_COMMIT_TAG}"  # Use the tag from GitLab
      if [ -z "$TAG_NAME" ]; then
        echo "No tag found. Skipping release creation."
        exit 0
      fi
      RELEASE_NOTES=$(cat RELEASE_NOTES.md)  # Read release notes from a file
      curl -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"Release $TAG_NAME\",\"body\":\"$RELEASE_NOTES\"}" \
        "https://api.github.com/repos/RauchenwaldC/homebridge-qbittorrent-plugin/releases"
  only:
    - tags
