stages:
  - sync

sync_to_github:  
  stage: sync
  script:
    - |
      if ! git remote get-url github; then
        git remote add github https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RauchenwaldC/homebridge-qbittorrent-plugin.git
      fi
    - |
      git config user.email "support@c18d.com"  # Set a CI-specific email for the local repo
      git config user.name "CI Runner"          # Set a CI-specific username for the local repo
      git fetch origin master  # Fetch the latest changes from GitLab
      git checkout master       # Switch to the master branch
      git push github master --force  # Push the master branch to GitHub
  only:
    - master