stages:
  - sync

sync_to_github:  
  stage: sync
  script:
    - |
      if ! git remote get-url github; then
        git remote add github https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RauchenwaldC/homebridge-qbittorrent-plugin.git
      fi
    - |
      git config user.email "support@c18d.com"
      git config user.name "CI Runner"
      git fetch origin master
      git checkout master
      git pull origin master    # Update local branch with the latest changes
      git push github master    # Push to GitHub without force
  only:
    - master
