stages:
  - sync

sync_to_github:  
  stage: sync
  script:
    - |
      if ! git remote get-url github; then
        git remote add github https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RauchenwaldC/homebridge-qbittorrent-plugin.git
      fi
    - |
      git config user.email "support@c18d.com"  # Set a CI-specific email for the local repo
      git config user.name "CI Runner"          # Set a CI-specific username for the local repo
      if [ $(git branch --list main) ]; then
        # If the main branch exists, push it
        git push github main --force
      else
        # If no branches exist, create a new commit, create the main branch, and push to main
        echo "# Homebridge qBittorrent Plugin" >> README.md
        git add README.md
        git commit -m "Initial commit"
        git checkout -b main  # Create and switch to the main branch
        git push --set-upstream github main --force  # Set upstream while pushing
      fi
  only:
    - master